# Generated by doctest: do not edit by hand
# Please edit file in R/tab.R

test_that("Example: tab_n", {
  # Created from @doctest for `tab_n`
  # Source file: R/tab.R
  # Source line: 88
  expect_snapshot(tab_n(1:10, 5))
  tab_n(1:10, 4)
})

