# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: fillet", {
  # Created from @doctest for `fillet`
  # Source file: R/chop.R
  # Source line: 254
  expect_snapshot(fillet(1:10, c(2, 5, 8)))
})

