# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop_n", {
  # Created from @doctest for `chop_n`
  # Source file: R/chop.R
  # Source line: 547
  expect_length(unique(chop_n(1:10, 5)), 2)
  x <- rep(1:2, each = 3)
  expect_warning(chop_n(x, 2))
})

