# Generated by doctest: do not edit by hand
# Please edit file in R/tab.R

test_that("Example: tab_width", {
  # Created from @doctest for `tab_width`
  # Source file: R/tab.R
  # Source line: 38
  expect_snapshot(tab_width(1:10, 2, start = 0))
})

