# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop_pretty", {
  # Created from @doctest for `chop_pretty`
  # Source file: R/chop.R
  # Source line: 414
  expect_snapshot(chop_pretty(1:10))
  chop(1:10, brk_pretty(n = 5, high.u.bias = 0))
})

