# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop_width", {
  # Created from @doctest for `chop_width`
  # Source file: R/chop.R
  # Source line: 445
  expect_snapshot(chop_width(1:10, 2))
  expect_match(levels(chop_width(1:10, 2, start = 0)), "[0, 2)", fixed = TRUE, all = FALSE)
  expect_match(levels(chop_width(1:9, -2)), "(7, 9]", fixed = TRUE, all = FALSE)
  chop(1:10, brk_width(2, 0))
})

