# Generated by doctest: do not edit by hand
# Please edit file in R/labels.R

test_that("Example: lbl_seq", {
  # Created from @doctest for `lbl_seq`
  # Source file: R/labels.R
  # Source line: 520
  expect_match(levels(chop(1:10, c(2, 5, 8), lbl_seq())), "a", all = FALSE)
  expect_match(levels(chop(1:10, c(2, 5, 8), lbl_seq("i."))), "i.", all = FALSE,
  fixed = TRUE)
  expect_match(levels(chop(1:10, c(2, 5, 8), lbl_seq("(A)"))), "(A)", all = FALSE,
  fixed = TRUE)
})

