# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop", {
  # Created from @doctest for `chop`
  # Source file: R/chop.R
  # Source line: 143
  expect_snapshot(chop(1:7, c(2, 4, 6)))
  expect_true(is.na(chop(1:7, c(2, 4, 6), extend = FALSE)[1]))
  expect_match(levels(chop(1:7, c(2, 4, 4, 6))), "{4}")
  expect_setequal(levels(chop(1:7, c(Lowest = 1, Low = 2, Mid = 4, High = 6))), c(
    "Lowest", "Low", "Mid", "High"))
  expect_setequal(levels(chop(1:7, c(2, 4, 6), labels = c("Lowest", "Low", "Mid",
    "High"))), c("Lowest", "Low", "Mid", "High"))
  expect_match(levels(chop(1:7, c(2, 4, 6), labels = lbl_dash())), em_dash())
  expect_equal(levels(chop(1:7, c(`<2` = 1, 2, 4, `>=6` = 6), labels = lbl_dash()))[
    1], "<2")
  chop(as.Date("2001-01-01") + 1:7, as.Date("2001-01-04"))
  expect_match(levels(suppressWarnings(chop(LETTERS[1:7], "D"))), "A.*D", all = FALSE)
})

