# Generated by doctest: do not edit by hand
# Please edit file in R/labels.R

test_that("Example: lbl_dash", {
  # Created from @doctest for `lbl_dash`
  # Source file: R/labels.R
  # Source line: 98
  expect_snapshot(chop(1:10, c(2, 5, 8), lbl_dash()))
  expect_snapshot(chop(1:10, c(2, 5, 8), lbl_dash(" to ", fmt = "%.1f")))
  expect_snapshot(chop(1:10, c(2, 5, 8), lbl_dash(first = "<{r}")))
  pretty <- (function(x) prettyNum(x, big.mark = ",", digits = 1))
  expect_snapshot(chop(runif(10) * 10000, c(3000, 7000), lbl_dash(" to ", fmt = pretty)))
})

