# Generated by doctest: do not edit by hand
# Please edit file in R/labels.R

test_that("Example: lbl_midpoints", {
  # Created from @doctest for `lbl_midpoints`
  # Source file: R/labels.R
  # Source line: 142
  expect_snapshot(chop(1:10, c(2, 5, 8), lbl_midpoints()))
})

