# Generated by doctest: do not edit by hand
# Please edit file in R/labels.R

test_that("Example: lbl_endpoints", {
  # Created from @doctest for `lbl_endpoints`
  # Source file: R/labels.R
  # Source line: 332
  expect_snapshot(chop(1:10, c(2, 5, 8), lbl_endpoints(left = TRUE)))
  expect_snapshot(chop(1:10, c(2, 5, 8), lbl_endpoints(left = FALSE)))
  if (requireNamespace("lubridate")) {
    expect_snapshot(tab_width(as.Date("2000-01-01") + 0:365, months(1), labels = lbl_endpoints(
      fmt = "%b")))
  }
  expect_length(levels(chop(1:3, 1:3, lbl_endpoints(left = FALSE))), 2)
})

