# Generated by doctest: do not edit by hand
# Please edit file in R/labels.R

test_that("Example: lbl_glue", {
  # Created from @doctest for `lbl_glue`
  # Source file: R/labels.R
  # Source line: 203
  expect_snapshot(tab(1:10, c(1, 3, 3, 7), label = lbl_glue("{l} to {r}", single = "Exactly {l}")))
  expect_snapshot(tab(1:10 * 1000, c(1, 3, 5, 7) * 1000, label = lbl_glue("{l}-{r}",
    fmt = function(x) prettyNum(x, big.mark = ","))))
  interval_left <- "{ifelse(l_closed, '[', '(')}"
  interval_right <- "{ifelse(r_closed, ']', ')')}"
  glue_string <- paste0(interval_left, "{l}", ", ", "{r}", interval_right)
  expect_snapshot(tab(1:10, c(1, 3, 3, 7), label = lbl_glue(glue_string, single = "{{{l}}}")))
})

