# Generated by doctest: do not edit by hand
# Please edit file in R/labels.R

test_that("Example: lbl_intervals", {
  # Created from @doctest for `lbl_intervals`
  # Source file: R/labels.R
  # Source line: 56
  expect_snapshot(tab(-10:10, c(-3, 0, 0, 3), labels = lbl_intervals()))
  set.seed(42)
  expect_snapshot(tab_evenly(runif(20), 10, labels = lbl_intervals(fmt = percent)))
})

