# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop_quantiles", {
  # Created from @doctest for `chop_quantiles`
  # Source file: R/chop.R
  # Source line: 292
  expect_snapshot(chop_quantiles(1:10, 1:3 / 4))
  chop_quantiles(1:10, c(Q1 = 0, Q2 = 0.25, Q3 = 0.5, Q4 = 0.75))
  chop(1:10, brk_quantiles(1:3 / 4))
  chop_deciles(1:10)
  chop_quantiles(1:10, 1:3 / 4, raw = TRUE)
})

