# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop_proportions", {
  # Created from @doctest for `chop_proportions`
  # Source file: R/chop.R
  # Source line: 512
  expect_match(as.character(chop_proportions(0:10, c(0.2, 0.8))), "[0, 2)", fixed = TRUE,
  all = FALSE)
  chop_proportions(0:10, c(Low = 0, Mid = 0.2, High = 0.8))
})

