# Generated by doctest: do not edit by hand
# Please edit file in R/tab.R

test_that("Example: tab_mean_sd", {
  # Created from @doctest for `tab_mean_sd`
  # Source file: R/tab.R
  # Source line: 108
  expect_snapshot(tab_mean_sd(1:10))
})

