# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop_equally", {
  # Created from @doctest for `chop_equally`
  # Source file: R/chop.R
  # Source line: 336
  expect_length(unique(chop_equally(1:10, 5)), 5)
})

