# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop_mean_sd", {
  # Created from @doctest for `chop_mean_sd`
  # Source file: R/chop.R
  # Source line: 374
  expect_snapshot(chop_mean_sd(1:10))
  chop(1:10, brk_mean_sd())
})

