# Generated by doctest: do not edit by hand
# Please edit file in R/labels.R

test_that("Example: lbl_discrete", {
  # Created from @doctest for `lbl_discrete`
  # Source file: R/labels.R
  # Source line: 407
  expect_match(names(tab(1:7, c(1, 3, 5), lbl_discrete())), "1(-|—)2", all = FALSE)
  expect_snapshot(tab(1:7, c(3, 5), lbl_discrete(first = "<= {r}")))
})

