# Generated by doctest: do not edit by hand
# Please edit file in R/breaks.R

test_that("Example: brk_width-for-datetime", {
  # Created from @doctest for `brk_width-for-datetime`
  # Source file: R/breaks.R
  # Source line: 138
  if (requireNamespace("lubridate")) {
    year2001 <- as.Date("2001-01-01") + 0:364
    expect_match(names(tab_width(year2001, months(1), labels = lbl_discrete(" to ",
      fmt = "%e %b"))), "31 Jan", all = FALSE)
  }
})

