# Generated by doctest: do not edit by hand
# Please edit file in R/tab.R

test_that("Example: tab_pretty", {
  # Created from @doctest for `tab_pretty`
  # Source file: R/tab.R
  # Source line: 125
  expect_snapshot(tab_pretty(1:10))
})

