# Generated by doctest: do not edit by hand
# Please edit file in R/tab.R

test_that("Example: tab", {
  # Created from @doctest for `tab`
  # Source file: R/tab.R
  # Source line: 5
  expect_snapshot(tab(1:10, c(2, 5, 8)))
})

