# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop_fn", {
  # Created from @doctest for `chop_fn`
  # Source file: R/chop.R
  # Source line: 583
  if (requireNamespace("scales")) {
    set.seed(42)
    expect_snapshot(chop_fn(rlnorm(10), scales::breaks_log(5)))
  }
})

