# Generated by doctest: do not edit by hand
# Please edit file in R/chop.R

test_that("Example: chop_evenly", {
  # Created from @doctest for `chop_evenly`
  # Source file: R/chop.R
  # Source line: 482
  expect_length(unique(chop_evenly(0:10, 5)), 5)
})

