# Generated by doctest: do not edit by hand
# Please edit file in R/breaks.R

test_that("Example: brk_manual", {
  # Created from @doctest for `brk_manual`
  # Source file: R/breaks.R
  # Source line: 324
  lbrks <- brk_manual(1:3, rep(TRUE, 3))
  chop(1:3, lbrks, extend = FALSE)
  rbrks <- brk_manual(1:3, rep(FALSE, 3))
  chop(1:3, rbrks, extend = FALSE)
  brks_singleton <- brk_manual(c(1, 2, 2, 3), c(TRUE, TRUE, FALSE, TRUE))
  chop(1:3, brks_singleton, extend = FALSE)
})

