# Generated by doctest: do not edit by hand
# Please edit file in R/tab.R

test_that("Example: tab_quantiles", {
  # Created from @doctest for `tab_quantiles`
  # Source file: R/tab.R
  # Source line: 138
  set.seed(42)
  expect_snapshot(tab_quantiles(rnorm(100), probs = 1:3 / 4, raw = TRUE))
})

