// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// categorize_impl
IntegerVector categorize_impl(NumericVector x, NumericVector breaks, LogicalVector left);
RcppExport SEXP _santoku_categorize_impl(SEXP xSEXP, SEXP breaksSEXP, SEXP leftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type left(leftSEXP);
    rcpp_result_gen = Rcpp::wrap(categorize_impl(x, breaks, left));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_santoku_categorize_impl", (DL_FUNC) &_santoku_categorize_impl, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_santoku(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
