# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

categorize <- function(x, breaks) {
    .Call(`_santoku_categorize`, x, breaks)
}

old_categorize <- function(x, breaks) {
    .Call(`_santoku_old_categorize`, x, breaks)
}

